#travis

language: java
jdk: openjdk8

branches:
  only:
    - ask

before_install:
  - chmod +x gradlew

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice ./*
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: ask-springboot-webservice
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true


#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      -tjdrud3632@naver.com

